// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ChatroomRepository is an autogenerated mock type for the ChatroomRepository type
type ChatroomRepository struct {
	mock.Mock
}

// NewChatroomRepository creates a new instance of ChatroomRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChatroomRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChatroomRepository {
	mock := &ChatroomRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
