// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	domain "api-server/domain"

	mock "github.com/stretchr/testify/mock"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

type AuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthService) EXPECT() *AuthService_Expecter {
	return &AuthService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: name, password
func (_m *AuthService) Login(name string, password string) *domain.User {
	ret := _m.Called(name, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *domain.User
	if rf, ok := ret.Get(0).(func(string, string) *domain.User); ok {
		r0 = rf(name, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	return r0
}

// AuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - name string
//   - password string
func (_e *AuthService_Expecter) Login(name interface{}, password interface{}) *AuthService_Login_Call {
	return &AuthService_Login_Call{Call: _e.mock.On("Login", name, password)}
}

func (_c *AuthService_Login_Call) Run(run func(name string, password string)) *AuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *AuthService_Login_Call) Return(_a0 *domain.User) *AuthService_Login_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthService_Login_Call) RunAndReturn(run func(string, string) *domain.User) *AuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: name, password
func (_m *AuthService) Register(name string, password string) *domain.User {
	ret := _m.Called(name, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *domain.User
	if rf, ok := ret.Get(0).(func(string, string) *domain.User); ok {
		r0 = rf(name, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	return r0
}

// AuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type AuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - name string
//   - password string
func (_e *AuthService_Expecter) Register(name interface{}, password interface{}) *AuthService_Register_Call {
	return &AuthService_Register_Call{Call: _e.mock.On("Register", name, password)}
}

func (_c *AuthService_Register_Call) Run(run func(name string, password string)) *AuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *AuthService_Register_Call) Return(_a0 *domain.User) *AuthService_Register_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthService_Register_Call) RunAndReturn(run func(string, string) *domain.User) *AuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
