// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	domain "api-server/domain"

	mock "github.com/stretchr/testify/mock"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

type AuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthService) EXPECT() *AuthService_Expecter {
	return &AuthService_Expecter{mock: &_m.Mock}
}

// FindUserById provides a mock function with given fields: id
func (_m *AuthService) FindUserById(id uint) *domain.User {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindUserById")
	}

	var r0 *domain.User
	if rf, ok := ret.Get(0).(func(uint) *domain.User); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	return r0
}

// AuthService_FindUserById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserById'
type AuthService_FindUserById_Call struct {
	*mock.Call
}

// FindUserById is a helper method to define mock.On call
//   - id uint
func (_e *AuthService_Expecter) FindUserById(id interface{}) *AuthService_FindUserById_Call {
	return &AuthService_FindUserById_Call{Call: _e.mock.On("FindUserById", id)}
}

func (_c *AuthService_FindUserById_Call) Run(run func(id uint)) *AuthService_FindUserById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *AuthService_FindUserById_Call) Return(_a0 *domain.User) *AuthService_FindUserById_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthService_FindUserById_Call) RunAndReturn(run func(uint) *domain.User) *AuthService_FindUserById_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByNameAndPassword provides a mock function with given fields: name, password
func (_m *AuthService) FindUserByNameAndPassword(name string, password string) *domain.User {
	ret := _m.Called(name, password)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByNameAndPassword")
	}

	var r0 *domain.User
	if rf, ok := ret.Get(0).(func(string, string) *domain.User); ok {
		r0 = rf(name, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	return r0
}

// AuthService_FindUserByNameAndPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByNameAndPassword'
type AuthService_FindUserByNameAndPassword_Call struct {
	*mock.Call
}

// FindUserByNameAndPassword is a helper method to define mock.On call
//   - name string
//   - password string
func (_e *AuthService_Expecter) FindUserByNameAndPassword(name interface{}, password interface{}) *AuthService_FindUserByNameAndPassword_Call {
	return &AuthService_FindUserByNameAndPassword_Call{Call: _e.mock.On("FindUserByNameAndPassword", name, password)}
}

func (_c *AuthService_FindUserByNameAndPassword_Call) Run(run func(name string, password string)) *AuthService_FindUserByNameAndPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *AuthService_FindUserByNameAndPassword_Call) Return(_a0 *domain.User) *AuthService_FindUserByNameAndPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthService_FindUserByNameAndPassword_Call) RunAndReturn(run func(string, string) *domain.User) *AuthService_FindUserByNameAndPassword_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: name, password
func (_m *AuthService) Register(name string, password string) *domain.User {
	ret := _m.Called(name, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *domain.User
	if rf, ok := ret.Get(0).(func(string, string) *domain.User); ok {
		r0 = rf(name, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	return r0
}

// AuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type AuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - name string
//   - password string
func (_e *AuthService_Expecter) Register(name interface{}, password interface{}) *AuthService_Register_Call {
	return &AuthService_Register_Call{Call: _e.mock.On("Register", name, password)}
}

func (_c *AuthService_Register_Call) Run(run func(name string, password string)) *AuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *AuthService_Register_Call) Return(_a0 *domain.User) *AuthService_Register_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthService_Register_Call) RunAndReturn(run func(string, string) *domain.User) *AuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
